export const ADD_COUNTER = "ADD_COUNTER";
export const REDUCE_COUNTER = "REDUCE_COUNTER";
export const SUM_COUNTER = "SUM_COUNTER";
export const SUBTRACT_COUNTER = "SUBTRACT_COUNTER";
export const MULTIPLY_COUNTER = "MULTIPLY_COUNTER";
export const DIVIDE_COUNTER = "DIVIDE_COUNTER";
